# Generated by Django 5.2.14 on 2026-05-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_auditlog_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
