# Generated by Django 5.2.14 on 2026-05-14 11:36

import django.db.models.deletion
import django_mongodb_backend.fields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Africa', 'Africa'), ('Europe', 'Europe'), ('Americas', 'Americas'), ('Asia', 'Asia'), ('Middle_East', 'Middle East'), ('Multilateral', 'Multilateral')], max_length=20)),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('working_week_start', models.IntegerField(default=1)),
                ('working_week_end', models.IntegerField(default=5)),
                ('work_start_time', models.TimeField(default='09:00')),
                ('work_end_time', models.TimeField(default='17:00')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'db_table': 'missions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('routing_department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Facilities', 'Facilities'), ('Finance', 'Finance'), ('Admin', 'Admin')], default='IT', help_text='Department queue this category routes to (SRS 3.4 / pdf2)', max_length=20)),
                ('auto_escalation_hours', models.IntegerField(blank=True, help_text='Hours before auto-escalation to HQ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ticket Category',
                'verbose_name_plural': 'Ticket Categories',
                'db_table': 'ticket_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('holiday_name', models.CharField(max_length=100)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='missions.mission')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holiday_calendars',
                'ordering': ['holiday_date'],
                'unique_together': {('mission', 'holiday_date')},
            },
        ),
    ]
