# Generated by Django 5.2.14 on 2026-05-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='seq_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
