# Generated by Django 6.0.5 on 2026-05-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_history', to='tickets.ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='assettickethistory',
            unique_together={('asset', 'ticket')},
        ),
    ]
