# Generated by Django 5.2.14 on 2026-05-14 11:36

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Requester', 'Requester'), ('Agent', 'Agent'), ('Mission_Admin', 'Mission Admin'), ('HQ_Super_Admin', 'HQ Super Admin')], default='Requester', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('IT', 'IT'), ('HR', 'HR'), ('Facilities', 'Facilities'), ('Finance', 'Finance'), ('Admin', 'Admin')], max_length=20, null=True)),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='missions.mission')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('scope_all', models.BooleanField(default=True)),
                ('scope_categories', models.JSONField(blank=True, default=list)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_as_delegator', to=settings.AUTH_USER_MODEL)),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_as_deputy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delegations',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='OnBehalfOfGrant',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obo_grants_as_assistant', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obo_grants', to='missions.mission')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obo_grants_as_official', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'On-Behalf-Of grant',
                'db_table': 'on_behalf_of_grants',
                'unique_together': {('mission', 'assistant', 'official')},
            },
        ),
    ]
